database:
  type: mysql
  connector: mysqlconnector
  host: localhost
  port: 3306
  username: root
  password: m4camo38A!
  db_name: purse_ohlcv

airflow:
  username: purse
  password: purse

universe:
  tickers:
    - "ADAUSDT"
    - "ATOMUSDT"
    - "AVAXUSDT"
    - "BCHUSDT"
    - "BNBUSDT"
    - "BTCUSDT"
    - "DOGEUSDT"
    - "DOTUSDT"
    - "ETCUSDT"
    - "ETHUSDT"
    - "FILUSDT"
    - "LINKUSDT"
    - "LTCUSDT"
    - "MKRUSDT"
    - "NEARUSDT"
    - "SOLUSDT"
    - "TRXUSDT"
    - "UNIUSDT"
    - "XLMUSDT"
    - "XRPUSDT"
